Fix makefile and add missing ftp structure
ONSdigital/sdx-compose pull request #36
Opened 2017-07-06 10:53 UTC by gemmai95

2017-07-06 10:55 UTC, JamesGardiner requested changes
Could you update the changelog please?

2017-07-06 12:27 UTC, necrophonic commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
Why changing from the parameterised call? The local installed python3 may not be available as a specific `python` command in the path

2017-07-06 13:10 UTC, JamesGardiner commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
This repo states that users should have an activated virtual environment before running, that has been setup to use Python3.

2017-07-06 13:12 UTC, JamesGardiner commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
But, to be honest, I don't even know why we are generating keys. Don't we have test keys in compose?

2017-07-06 13:13 UTC, necrophonic commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
It's inconsistent with the rest of the makefile though that still uses `${PYTHON3}`

2017-07-06 13:15 UTC, JamesGardiner commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
That should be taken out. README also needs updating as it still references PYTHON3 variable @gemmai95

2017-07-07 06:54 UTC, warrenbailey commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
I actually find it really annoy you need a virtual environment to run a docker-compose script, it shouldn't even be using Python, all it's doing is building and starting docker containers.

I agree with James, why are we even generating keys? Why not just use the test keys? We could remove all that and keep the script much simpler.

Though if we're determined to create keys just convert the configure.py script to a bash script, it's basically 4 openssl commands. Then we don't have to create a virtual environments to install sdx-common and we probably don't even need Python on the path at all.  

Either of these options simplifies a Makefile that at the minute doesn't work out of the box.

2017-07-07 08:43 UTC, necrophonic commented on Makefile
> +	cd ${SDX_HOME}/sdx-ops && python sdx/ops/configure.py --env > ${SDX_HOME}/sdx-compose/env/private.env ;cd -
The bash script is probably the way to go as Warran suggests 👍 

I would just check keys in, but even if they're technically fake and not used for anything there's always a risk one day they _may_ actually get used, plus any security scans we do of our repos would probably be false-positiving by picking them up.

2017-07-10 09:41 UTC, necrophonic submitted a review, later dismissed
Ok to go as - is. Will raise a tech debt card to create a bash script for the keys as mentioned in the review.

2017-07-10 10:42 UTC, JamesGardiner approved these changes

2017-07-10 10:50 UTC, merged