Added feedback table
ONSdigital/sdx-compose pull request #38
Opened 2017-07-13 09:15 UTC by tej99

2017-07-13 12:17 UTC, JamesGardiner requested changes
Can you update the CHANGELOG? Also, are 25 chars guaranteed to always be enough?

2017-07-18 11:12 UTC, warrenbailey submitted a review, later dismissed

2017-07-18 11:16 UTC, warrenbailey commented
Good point @JamesGardiner I missed that, the SQLAlchemy doesn't restrict the size of the String so I think it's possible that it could exceed 25 chars. (https://github.com/ONSdigital/sdx-store/pull/62/files)

2017-07-18 11:17 UTC, warrenbailey commented on postgres/schema.sql
> +CREATE TABLE IF NOT EXISTS feedback_responses (id SERIAL, ts timestamp WITH time zone DEFAULT NOW(), invalid boolean DEFAULT NULL, data jsonb, survey char(25), period char(25));
What's the reason for 25 chars?

2017-07-18 12:28 UTC, tej99 commented on postgres/schema.sql
> +CREATE TABLE IF NOT EXISTS feedback_responses (id SERIAL, ts timestamp WITH time zone DEFAULT NOW(), invalid boolean DEFAULT NULL, data jsonb, survey char(25), period char(25));
I'm not sure if you can create a column with data type char without having a size and 25 chars seemed sensible. I can change the SQLAlchemy to restrict the size to 25? Unless there's a better way to do this?

2017-07-19 09:27 UTC, JamesGardiner commented on postgres/schema.sql
> +CREATE TABLE IF NOT EXISTS feedback_responses (id SERIAL, ts timestamp WITH time zone DEFAULT NOW(), invalid boolean DEFAULT NULL, data jsonb, survey char(25), period char(25));
Use an `@property` and validate the string length in an `@property.setter` method, raising an exception if necessary

2017-07-19 11:36 UTC, tej99 commented on postgres/schema.sql
> +CREATE TABLE IF NOT EXISTS feedback_responses (id SERIAL, ts timestamp WITH time zone DEFAULT NOW(), invalid boolean DEFAULT NULL, data jsonb, survey char(25), period char(25));
SQLAlchemy handles that

2017-07-19 12:02 UTC, JamesGardiner submitted a review, later dismissed

2017-07-19 13:05 UTC, JamesGardiner approved these changes

2017-07-19 13:05 UTC, merged