All rabbit dependent services should start on start-up
ONSdigital/sdx-compose pull request #58
Opened 2018-05-22 14:37 UTC by ryangrundy7

Currently this PR is using an image from my dockerhub account until another PR has been put in so this shouldn't be merged first. With this PR all services should be able to start on start-up.

PR first:
https://github.com/ONSdigital/dockers/pull/20

To test:
- Run make start and all rabbit dependent services should be up and running

2018-05-22 14:52 UTC, MIslam92 submitted a review, later dismissed

2018-05-22 14:52 UTC, MIslam92 commented on Makefile
> +	docker-compose run  --rm start_dependencies
Small nitpick, extra space here not needed?

2018-05-23 07:18 UTC, dcdarrell9 submitted a review, later dismissed
All seems good 👍

2018-05-23 14:16 UTC, dcdarrell9 submitted a review, later dismissed

2018-05-24 10:23 UTC, insacuri submitted a review, later dismissed

2018-05-24 10:25 UTC, insacuri submitted a review, later dismissed

2018-05-24 10:27 UTC, dcdarrell9 requested changes
Changelog needs updating

2018-05-24 10:32 UTC, dcdarrell9 approved these changes

2018-05-24 11:48 UTC, merged