Updated README.md
ONSdigital/sdx-compose pull request #71
Opened 2020-02-13 11:11 UTC by bkhan2

I made some changes to the README to help new starters, like me, spin up sdx.

2020-02-13 11:38 UTC, insacuri requested changes

2020-02-13 11:38 UTC, insacuri commented on README.md
> +HOW-TO:
I wouldn't bother with the 'how to use vi' section.

2020-02-13 11:38 UTC, insacuri commented on README.md
> +Export a ``SDX_HOME`` environment variable.
I'd change this to:
There needs to be an SDX_HOME environment variable pointed to where you will have all the SDX repos checked out to.  To do this, add   `export SDX_HOME=$HOME/projects/sdx` (the location is an example but you can have it checked out anywhere you want) to your .bash_profile (if using bash).

2020-02-13 11:38 UTC, insacuri commented on README.md
> +cd into `/Users/[NAME]/projects/sdx` and run the following:
Change this to:
Do `cd $SDX_HOME` and run the following:

2020-02-13 11:38 UTC, insacuri commented on README.md
> +Make a projects directory e.g. `/Users/[NAME]/projects`
Remove these 2 lines for the change I mentioned below

2020-02-13 11:38 UTC, insacuri commented on README.md
>  Set up a virtual environment using Python3 and ensure you activate it.
Can you remove this line, it's not true.

2020-02-21 14:37 UTC, bkhan2 commented
Changes made

2020-02-24 10:42 UTC, insacuri requested changes

2020-02-24 10:42 UTC, insacuri commented on README.md
> +Open your .bash_profile and add the line: ``export SDX_HOME=$HOME/[LOCATION OF SDX FOLDER]``
This line and the other changed line (line 18) needs to change.  The line 18 line doesn't make any sense.  This line isn't accurate either.  Assuming you follow the instructions you'd have SDX_HOME be `$HOME/users/name/sdx` which doesn't exist.

Just change these lines to:
Open your .bash_profile and add the line: `export SDX_HOME=[LOCATION OF SDX FOLDER]`
Then apply the changes to the bash_profile to your session by doing `. ~/.bash_profile`

2020-02-26 12:21 UTC, insacuri requested changes

2020-02-26 12:21 UTC, insacuri commented on README.md
> +Apply these changes to your bash_profile by doing ``~/.bash_profile``
This line is wrong, the command is:
`. ~/.bash_profile`

Also, why are you using pairs of backticks?  Use either 1 or 3

2020-02-27 13:19 UTC, insacuri approved these changes

2020-03-02 09:29 UTC, warrenbailey approved these changes

2020-03-03 09:35 UTC, merged